In [2]:
import pandas as pd
import numpy as np

In [3]:
csv_path = "20152020.csv"

# Import the CSV into a pandas DataFrame
nba_df = pd.read_csv(csv_path, low_memory=False)
nba_df

,2019,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2019,Steven Adams\adamsst01,C,26,OKC,58,58,1564,262,443,...,0.590,196,347,543,141,50,65,86,111,633
1,2019,Bam Adebayo\adebaba01,PF,22,MIA,65,65,2235,408,719,...,0.690,165,518,683,333,78,85,185,164,1053
2,2019,LaMarcus Aldridge\aldrila01,C,34,SAS,53,53,1754,391,793,...,0.827,103,289,392,129,36,87,74,128,1001
3,2019,Nickeil Alexander-Walker\alexani01,SG,21,NOP,41,0,501,77,227,...,0.607,8,72,80,74,11,7,40,46,211
4,2019,Grayson Allen\allengr01,SG,24,MEM,30,0,498,79,176,...,0.857,5,61,66,43,6,1,23,36,221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3164,2015,Joe Young\youngjo01,PG,23,IND,41,0,384,62,169,...,0.800,6,44,50,65,15,0,33,30,154
3165,2015,Nick Young\youngni01,SG,30,LAL,54,2,1033,126,372,...,0.829,14,83,97,34,23,7,30,50,392
3166,2015,Thaddeus Young\youngth01,PF,27,BRK,73,73,2407,495,963,...,0.644,176,484,660,135,112,37,136,182,1102
3167,2015,Cody Zeller\zelleco01,C,23,CHO,73,60,1774,231,437,...,0.754,138,317,455,71,57,63,68,204,638
3168,2015,Tyler Zeller\zellety01,C,26,BOS,60,3,710,138,290,...,0.815,62,116,178,29,10,22,46,97,364

In [4]:
#removing the backslash
nba_df["Player"]= nba_df["Player"].str.split("\\", n = 1, expand = True)

In [5]:
nba_df.head()

,2019,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2019,Steven Adams,C,26,OKC,58,58,1564,262,443,...,0.590,196,347,543,141,50,65,86,111,633
1,2019,Bam Adebayo,PF,22,MIA,65,65,2235,408,719,...,0.690,165,518,683,333,78,85,185,164,1053
2,2019,LaMarcus Aldridge,C,34,SAS,53,53,1754,391,793,...,0.827,103,289,392,129,36,87,74,128,1001
3,2019,Nickeil Alexander-Walker,SG,21,NOP,41,0,501,77,227,...,0.607,8,72,80,74,11,7,40,46,211
4,2019,Grayson Allen,SG,24,MEM,30,0,498,79,176,...,0.857,5,61,66,43,6,1,23,36,221

In [6]:
#renaming year column
nba_df.rename(columns = {'2019':'year'}, inplace = True) 
nba_df.head()

,year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2019,Steven Adams,C,26,OKC,58,58,1564,262,443,...,0.590,196,347,543,141,50,65,86,111,633
1,2019,Bam Adebayo,PF,22,MIA,65,65,2235,408,719,...,0.690,165,518,683,333,78,85,185,164,1053
2,2019,LaMarcus Aldridge,C,34,SAS,53,53,1754,391,793,...,0.827,103,289,392,129,36,87,74,128,1001
3,2019,Nickeil Alexander-Walker,SG,21,NOP,41,0,501,77,227,...,0.607,8,72,80,74,11,7,40,46,211
4,2019,Grayson Allen,SG,24,MEM,30,0,498,79,176,...,0.857,5,61,66,43,6,1,23,36,221

In [7]:
nba_df.to_csv('cleannba_df.csv', index=False)

PermissionError: [Errno 13] Permission denied: 'clean20152020.csv'