In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
csv_path = "clean20152020.csv"

# Import the CSV into a pandas DataFrame
nba_df = pd.read_csv(csv_path, low_memory=False)
nba_df

,year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,All Star
0,2018,James Harden,PG,29,HOU,78,78,2867,843,1909,...,66,452,518,586,158,58,387,244,2818,Yes
1,2016,Russell Westbrook,PG,28,OKC,81,81,2802,824,1941,...,137,727,864,840,132,31,438,190,2558,Yes
2,2015,James Harden,SG,26,HOU,82,82,3125,710,1617,...,63,438,501,612,139,51,374,229,2376,Yes
3,2015,Stephen Curry,PG,27,GSW,79,79,2700,805,1598,...,68,362,430,527,169,15,262,161,2375,Yes
4,2016,James Harden,PG,27,HOU,81,81,2947,674,1533,...,95,564,659,907,121,38,464,215,2356,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3164,2015,James Ennis,SF,25,MIA,3,0,7,0,0,...,0,0,0,1,0,0,0,1,0,NaN
3165,2015,Erick Green,PG,24,DEN,3,0,7,0,1,...,0,1,1,1,0,0,0,0,0,NaN
3166,2015,J.J. O'Brien,SF,23,UTA,2,0,6,0,1,...,0,1,1,0,1,0,0,1,0,NaN
3167,2015,Nate Robinson,PG,31,NOP,2,1,23,0,1,...,0,0,0,4,1,0,0,5,0,NaN
3168,2015,Jarnell Stokes,C,22,MEM,2,0,4,0,0,...,1,1,2,0,0,0,0,0,0,NaN

In [21]:
nba_df.fillna('no', inplace=True)

In [16]:
nba_df.head(20)

,year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,All Star
0,2018,James Harden,PG,29,HOU,78,78,2867,843,1909,...,66,452,518,586,158,58,387,244,2818,Yes
1,2016,Russell Westbrook,PG,28,OKC,81,81,2802,824,1941,...,137,727,864,840,132,31,438,190,2558,Yes
2,2015,James Harden,SG,26,HOU,82,82,3125,710,1617,...,63,438,501,612,139,51,374,229,2376,Yes
3,2015,Stephen Curry,PG,27,GSW,79,79,2700,805,1598,...,68,362,430,527,169,15,262,161,2375,Yes
4,2016,James Harden,PG,27,HOU,81,81,2947,674,1533,...,95,564,659,907,121,38,464,215,2356,Yes
5,2017,LeBron James,PF,33,CLE,82,82,3026,857,1580,...,97,612,709,747,116,71,347,136,2251,Yes
6,2016,Isaiah Thomas,PG,27,BOS,76,76,2569,682,1473,...,43,162,205,448,70,13,210,167,2199,Yes
7,2017,James Harden,SG,28,HOU,72,72,2551,651,1449,...,41,348,389,630,126,50,315,169,2191,Yes
8,2018,Paul George,SF,28,OKC,77,77,2841,707,1614,...,105,523,628,318,170,34,205,214,2159,Yes
9,2017,Anthony Davis,PF,24,NOP,75,75,2727,780,1462,...,187,645,832,174,115,193,162,159,2110,Yes
10,2018,Kemba Walker,PG,28,CHO,82,82,2863,731,1684,...,52,309,361,484,102,34,211,131,2102,Yes
11,2018,Bradley Beal,SG,25,WAS,82,82,3028,764,1609,...,89,322,411,448,121,58,224,226,2099,Yes
12,2016,Anthony Davis,C,23,NOP,75,75,2708,770,1526,...,172,712,884,157,94,167,181,168,2099,Yes
13,2019,James Harden,SG,30,HOU,61,61,2241,603,1386,...,64,324,388,450,106,53,273,206,2096,Yes
14,2018,Damian Lillard,PG,28,POR,80,80,2838,681,1533,...,68,303,371,551,88,34,212,148,2067,Yes
15,2016,Karl-Anthony Towns,C,21,MIN,82,82,3030,802,1480,...,296,711,1007,220,56,103,212,241,2061,no
16,2015,Kevin Durant,SF,27,OKC,72,72,2578,698,1381,...,45,544,589,361,69,85,250,137,2029,Yes
17,2017,Russell Westbrook,PG,29,OKC,80,80,2914,757,1687,...,152,652,804,820,147,20,381,200,2028,Yes
18,2018,Kevin Durant,SF,30,GSW,78,78,2702,721,1383,...,33,464,497,457,58,84,225,155,2027,Yes
19,2016,Damian Lillard,PG,26,POR,75,75,2694,661,1488,...,46,322,368,440,68,20,197,152,2024,no

In [37]:
result_df = nba_df.sort_values('year')

result_df.head(44)

sorted_df = result_df.sort_values('year')
cleaner_nba = sorted_df.drop_duplicates()


cleaner_nba.to_csv('nba_df.csv', index=False)

In [42]:
cleaner_nba.rename(columns = {'All Star':'All_Star'}, inplace = True)

In [44]:
cleaner_nba.All_Star.replace(('Yes', 'no'), (1, 0), inplace=True)

cleaner_nba

,year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,All_Star
3168,2015,Jarnell Stokes,C,22,MEM,2,0,4,0,0,...,1,1,2,0,0,0,0,0,0,0
2302,2015,Jordan McRae,PG,24,TOT,22,1,195,34,78,...,4,16,20,25,3,1,15,17,99,0
2673,2015,Mario Chalmers,PG,29,MIA,6,0,120,10,32,...,1,13,14,19,8,1,9,16,33,0
258,2015,Marcus Morris,SF,26,DET,80,80,2856,410,945,...,91,313,404,201,67,23,140,170,1131,0
257,2015,Draymond Green,PF,25,GSW,81,81,2808,401,819,...,134,635,769,598,119,113,259,240,1131,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222,2019,Alec Burks,SG,28,PHI,11,0,222,39,100,...,6,30,36,20,8,0,9,13,118,0
872,2019,Rudy Gay,PF,33,SAS,60,5,1287,222,502,...,56,266,322,101,26,28,78,89,601,0
2067,2019,Jae Crowder,SF,29,MIA,13,1,373,50,114,...,8,68,76,26,20,7,8,41,155,0
3067,2019,Matt Mooney,SG,22,CLE,4,0,19,1,4,...,0,3,3,1,2,1,0,1,2,0
2153,2019,Dante Exum,SG,24,CLE,24,1,402,46,96,...,9,46,55,33,12,6,21,30,135,0